### ISSUE TITLE
How to uninstall this script?

### ISSUE THREAD

**Issue by griffin-warrior** [JessThrysoee/synology-letsencrypt#1]
First, thanks for your sharing. 
I just tried this script and it didn't work. Then I found that my DSM was 6.2.3, maybe not compatible with this script. 
Now I wanna remove it from my DSM. What should I do?

**Comment by JessThrysoee** [comment]
Sorry to hear that it isn't working for you. How did it fail? It should run on DSM 6 and 7, although I have upgraded to DSM 7 so I can't test it on your version.
 
I have added an uninstall.sh script.

**Comment by griffin-warrior** [comment]
Thanks. 

```bash
sudo /usr/local/bin/synology-letsencrypt.sh
```
This is the failure log:

> 2021/12/28 15:59:13 [INFO] [xxx.xxx] acme: Obtaining bundled SAN certificate
> 2021/12/28 15:59:15 [INFO] [xxx.xxx] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/62710656480
> 2021/12/28 15:59:15 [INFO] [xxx.xxx] acme: Could not find solver for: tls-alpn-01
> 2021/12/28 15:59:15 [INFO] [xxx.xxx] acme: Could not find solver for: http-01
> 2021/12/28 15:59:15 [INFO] [xxx.xxx] acme: use dns-01 solver
> 2021/12/28 15:59:15 [INFO] [xxx.xxx] acme: Preparing to solve DNS-01
> 2021/12/28 15:59:16 [INFO] [xxx.xxx] acme: Cleaning DNS-01 challenge
> 2021/12/28 15:59:17 [WARN] [xxx.xxx] acme: cleaning up failed: cloudflare: failed to find zone xxx.xxx.: ListZonesContext command failed: HTTP status 400: Invalid request headers (6003)
> 2021/12/28 15:59:17 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/62710656480
> 2021/12/28 15:59:17 Could not obtain certificates:
>         error: one or more domains had a problem:
> [xxx.xxx] [xxx.xxx] acme: error presenting token: cloudflare: failed to find zone xxx.xxx.: | ListZonesContext command failed: HTTP status 400: Invalid request headers (6003)
