### ISSUE TITLE
Ran Script  and Certificate is not applied on Login

### ISSUE THREAD

**Issue by lethalox** [JessThrysoee/synology-letsencrypt#11]
So I ran the script and did not get an error.   I am using Cloudflare as my provider.   Last line is:

`2023/11/08 22:48:41 [INFO] [bigbox.foo.org] Server responded with a certificate.`

When I login to bigbox.foo.org.   The web interface is using the self-signed cert from Synology and the Certificate does not appear in Control Panel/Security/Certificates...    Is there something more I should be doing?   It is not obvious from the read me file. 

Obiviously foo.org is not my domain name. 

Much thx.

**Comment by JessThrysoee** [comment]
We need a little more information to be able to start offering suggestions.

What synology device do you have?
Which version of DSM are you running?

Does the files refered in `/usr/local/etc/synology-letsencrypt/hook` exist?
If they do, was the received certificate copied to a subdirectory of `/usr/syno/etc/certificate/_archive/` ?
Is that certificate referenced in `/usr/syno/etc/certificate/_archive/INFO` ?

**Comment by lethalox** [comment]
So I actually have 3 synologies.  All are on DSM 7.X (whatever is current).   And long story short.  On my "primary" synology the script was older.  I tried the instructions on the different one and it worked great.   So I reinstalled the script on originally machine, gave it a different FQDN and it worked as expected.   

So thank you very much!   The script is awesome, and number 2 on the script awesomeness right after drive compatibility. 

2 Minor suggestions on improvement, and feel free to ignore. 
1 -  On the documentation you should give an overview of what the script is actually doing.   
2 -  Multiple domains the setup seem weird.   Would it be cleaner to specify multiple domain in the env file and let the script handle the the creation and maintaining the directories?

Best and thank you again.

**Comment by maxhac03** [comment]
Weird. I have the latest script and I can see the files referenced in /usr/local/etc/synology-letsencrypt/hook and the cert is in /usr/syno/etc/certificate/_archive/.

However, the cert is not in /usr/syno/etc/certificate/_archive/INFO. I only see the self one from Synology and the Quick connect one. Also doesn't appear in the Web Interface.

DS220+ 7.2.1-69057 Update 3

**Comment by nandonov** [comment]
Hello,
I have the exact same issue. The certificates seems to have been generated and downloaded but they are not referenced into the INFO file.


DS1621+  DSM 7.2.1-69057 Update 3

> We need a little more information to be able to start offering suggestions.
> 
> What synology device do you have? Which version of DSM are you running?
> 
> Does the files refered in `/usr/local/etc/synology-letsencrypt/hook` exist? 
Yes!
> If they do, was the received certificate copied to a subdirectory of `/usr/syno/etc/certificate/_archive/` ? 
Yes!
> Is that certificate referenced in `/usr/syno/etc/certificate/_archive/INFO` ?
No

**Comment by JessThrysoee** [comment]
@maxhac03 @nandonov Are you guys running the script as root? Only root can update INFO:

```
ls -l /usr/syno/etc/certificate/_archive/INFO
-rw------- 1 root root 1023 XXXX X XX:XX /usr/syno/etc/certificate/_archive/INFO
```

If you are running from the Task Scheduler, then that also needs to run with elevated permissions,

<img width="531" alt="image" src="https://github.com/JessThrysoee/synology-letsencrypt/assets/238102/0c023313-2a3d-4f57-85b7-0052f6592da2">

**Comment by JessThrysoee** [comment]
The INFO file was only maintained on the first run. I have commited https://github.com/JessThrysoee/synology-letsencrypt/commit/f903826175f17e25073763f7ca556d7113f86366 that hopefully fixes this.

This issue is not very focused, so please open a new issue with your findings if the above doesn't fix your problem.
