### ISSUE TITLE
couple questions

### ISSUE THREAD

**Issue by cirrusflyer** [JessThrysoee/synology-letsencrypt#16]
Love your script - thanks.

Is there a way to name the cert so it shows up in the NAS as "Description"?

Any reason the certs don't default to ECC - ec256?  That seems to be the default for lego, but the script pulls rsa4096 by default.  I do know that DSM 6.x only supports rsa.

Can I force a renewal with a flag?

**Comment by JessThrysoee** [comment]
Added LEGO_OPTIONS so you can change the --key-type to you liking :-)

See https://github.com/JessThrysoee/synology-letsencrypt?tab=readme-ov-file#configuration

**Comment by cirrusflyer** [comment]
My bad!  I missed the LEGO_OPTIONS entirely.  Thanks

**Comment by JessThrysoee** [comment]
No no, I just added LEGO_OPTIONS so you didn't miss it :-)
