### ISSUE TITLE
Synology NAS DS418

### ISSUE THREAD

**Issue by cirrusflyer** [JessThrysoee/synology-letsencrypt#17]
Have a DS418 with a Realtek RTD1296 SoC, which should use linux_arm64 lego.  But the install script produces "Could not find lego download URL! Try a different architecture maybe? See 'bash -h'".  How could I modify the script to accept this or force this file?

**Comment by JessThrysoee** [comment]
What does `dpkg --print-architecture` output?

**Comment by cirrusflyer** [comment]
dpkg --print-architecture:
armel

When I installed software, it uses arm64.

**Comment by JessThrysoee** [comment]
Try
```
curl -sSL https://raw.githubusercontent.com/JessThrysoee/synology-letsencrypt/master/install.sh | bash -s -- -a arm64
```

**Comment by cirrusflyer** [comment]
That works!  Thanks
