### ISSUE TITLE
Generate fullchain.pem file

### ISSUE THREAD

**Issue by prabirshrestha** [JessThrysoee/synology-letsencrypt#22]
I would like to reuse the cert generated by synology-letsencrypt in traefik. Is it possible to generate fullchain.cer file at /usr/local/etc/synology-letsencrypt so we can easily reference it in traefik?

https://doc.traefik.io/traefik/https/tls/

**Comment by JessThrysoee** [comment]
`$cert_domain.crt` contains the full chain, so you can use that.

This is, fullchain.crt erroneously contains `$cert_domain.issuer.crt` twice.

You can verify with `openssl storeutl -noout -text -certs $cert_domain.crt` or look at the explanation https://github.com/go-acme/lego/issues/1264#issuecomment-702559799

See https://github.com/JessThrysoee/synology-letsencrypt/commit/36b85c1b234301082673999573088915e0c5bb11

**Comment by prabirshrestha** [comment]
Thanks for the quick fix. I was able to successfully use the certs in traefik.
