### ISSUE TITLE
Adding support for Squarespace domains

### ISSUE THREAD

**Issue by nathanaeljames** [JessThrysoee/synology-letsencrypt#25]
With the recent migration of all Google domains to Squarespace domains (cf. https://domains.google/), is there any way we can get Squarespace domains added to the list of supported DNS providers?

**Comment by pogzie** [comment]
You might want to file this request in https://github.com/go-acme/lego/issues

**Comment by JessThrysoee** [comment]
@nathanaeljames all the ACME challenge functionality is handled by `lego` so @pogzie (thanks!) is correct to referrer you to https://github.com/go-acme/lego/issues 

I'll close this, because it is really a `lego` feature request.
